### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by tavalin** [Spotifyd/spotifyd-http#1]
Can you provide instructions on how to use/run the software please as I don't seem to be able to get it to work.

I'm new to Rust/Cargo but I've tried both on a RPi2 running Raspbian Jessie as well as an Ubuntu 16.04 VM and I'm encountering issues with both (although different issues).
1. I've installed rust and cargo on both machines.
2. I've checked out the code.
3. I've run:

```
cd spotifyd-http
cargo run
```

With the RPi2 it seems to run out of memory during build i.e.

```
cargo run
Compiling syntex_syntax v0.38.0
Compiling syntex_syntax v0.37.0
Compiling syntex_syntax v0.39.0
Compiling vorbis-sys v0.0.8
Compiling librespot-protocol v0.1.0 (https://github.com/SimonPersson/librespot.git#4358c209)
Build failed, waiting for other jobs to finish...
```

With the Ubuntu box I get the following:

```
Updating git repository: 'https://www.github.com/SimonPersson/librespot.git'

failed to parse registry's information for: serde_json

Caused by: 
   the given version requirement is invalid
```

Any help on getting this up and running appreciated!

**Comment by SimonTeixidor** [comment]
The RPi2 issue I can't do anything about I'm afraid. I'm surprised that it'd use so much memory though!

On the Ubuntu box, what version of rustc and cargo are you running? I've only tested this on nightly, so you might want to try that.

**Comment by tavalin** [comment]
I've had a little bit of time to come back to this.  I wiped my Ubuntu VM and started again with the nightly version of cargo and rustc.

This allowed me to get past the previous error so I guess this issue should be considered closed (although I'm not getting compile spotify-http against librespot I think).
