### ISSUE TITLE
No bug but help on installation

### ISSUE THREAD

**Issue by sdomotica** [Spotifyd/spotifyd-http#10]
I'm quite newbie, could you help me on compiling and install it on Raspberry?
Thks a lot
Sandro

**Comment by SimonTeixidor** [comment]
Sure. First install Rust and Cargo, https://www.rust-lang.org/en-US/install.html.

Then run `cargo build --release` in the directory of this project.

The resulting binary can then be found in `target/release/spotifyd-http`.

Try that out and get back to me if you're struggling. I'll try to build and release automatically one day, as I'm doing with `spotifyd` already, but this should work for now.

**Comment by sdomotica** [comment]
I made the following step on Raspberry PI3 Jessie
curl https://sh.rustup.rs -sSf | sh

rebooted
git clone https://github.com/Spotifyd/spotifyd-http.git spotifyd-http
cd spotifyd-http
cargo build --release

and I had this error
Downloading syntex_pos v0.39.0
 Downloading quasi_codegen v0.16.0
 Downloading termios v0.2.2
   Compiling typeable v0.1.2
   Compiling bit-vec v0.4.3
   Compiling modifier v0.1.0
   Compiling httparse v1.1.2
   Compiling cfg-if v0.1.0
   Compiling bitflags v0.7.0
   Compiling linear-map v1.1.0
   Compiling semver v0.1.20
   Compiling unicode-xid v0.0.3
   Compiling byteorder v0.5.3
   Compiling protobuf v1.0.24
   Compiling traitobject v0.0.3
   Compiling getopts v0.2.14
   Compiling rustc-serialize v0.3.19
   Compiling rustc_version v0.1.7
   Compiling extprim v1.1.1
   Compiling tempfile v2.1.4
   Compiling unicase v1.4.0
   Compiling multimap v0.2.0
   Compiling bitflags v0.4.0
   Compiling libc v0.2.15
   Compiling lazy_static v0.2.1
   Compiling quick-error v1.1.0
   Compiling quick-error v0.2.2
   Compiling nix v0.5.1
   Compiling num_cpus v0.2.13
   Compiling net2 v0.2.26
   Compiling termios v0.2.2
   Compiling rpassword v0.2.3
   Compiling regex-syntax v0.3.4
   Compiling traitobject v0.0.1
   Compiling matches v0.1.2
   Compiling unicode-bidi v0.2.3
   Compiling syntex_pos v0.39.0
   Compiling syntex_pos v0.37.0
   Compiling dns-parser v0.3.2 (http://github.com/plietar/dns-parser#1dfc0655)
   Compiling slab v0.1.3
   Compiling num-traits v0.1.35
   Compiling lazy_static v0.1.16
   Compiling void v1.0.2
   Compiling groupable v0.2.0
   Compiling num-complex v0.1.35
   Compiling language-tags v0.2.2
   Compiling unicode-normalization v0.1.2
   Compiling winapi-build v0.1.1
   Compiling idna v0.1.0
   Compiling ws2_32-sys v0.2.1
   Compiling rand v0.3.14
   Compiling pkg-config v0.3.8
   Compiling url v1.2.0
   Compiling uuid v0.2.3
   Compiling itoa v0.1.1
   Compiling num-integer v0.1.32
   Compiling num-bigint v0.1.35
   Compiling num-iter v0.1.32
   Compiling kernel32-sys v0.2.2
   Compiling num-rational v0.1.35
   Compiling syntex_pos v0.38.0
   Compiling unsafe-any v0.4.1
   Compiling typemap v0.3.3
   Compiling serde v0.7.15
   Compiling plugin v0.2.6
   Compiling bytes v0.3.0
   Compiling num v0.1.35
   Compiling url v0.5.10
   Compiling gcc v0.3.35
   Compiling serde_json v0.7.4
   Compiling ogg-sys v0.0.9
   Compiling vorbis-sys v0.0.8
   Compiling liblmdb-sys v0.2.1
   Compiling shannon-sys v0.1.0 (https://github.com/plietar/rust-shannon#7000b3e4)
   Compiling shannon v0.1.1 (https://github.com/plietar/rust-shannon#7000b3e4)
   Compiling rust-crypto v0.2.36
   Compiling protobuf_build v0.1.1 (https://github.com/plietar/rust-protobuf-build.git#24d5a01c)
   Compiling bit-set v0.4.0
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `protobuf_build v0.1.1 (https://github.com/plietar/rust-protobuf-build.git#24d5a01c)`
process didn't exit successfully: `/home/pi/sdomotica/tmp/spotifyd-http/target/release/build/protobuf_build-f6ad515227645728/build-script-build` (exit code: 101                                                                 )
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"protobuf\"` did not exit successfully: exit c                                                                 ode: 1\n--- stdout\nPackage protobuf was not found in the pkg-config search path                                                                 .\nPerhaps you should add the directory containing `protobuf.pc\'\nto the PKG_CO                                                                 NFIG_PATH environment variable\nNo package \'protobuf\' found\n"', /buildslave/r                                                                 ust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.r                                                                 s:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.

pi@sdomotica2:~/sdomotica/tmp/spotifyd-http $

**Comment by SimonTeixidor** [comment]
Ah, you don't have the `protobuf` dependency on your system. Install it and try again:
`sudo apt-get install portaudio19-dev`

**Comment by sdomotica** [comment]
Little bit more compiling but now I have it

   Compiling syntex_syntax v0.39.0
   Compiling env_logger v0.3.4
   Compiling protobuf_build v0.1.1 (https://github.com/plietar/rust-protobuf-bui                                                       ld.git#24d5a01c)
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `protobuf_build v0.1.1 (https://github.com/plietar/rust-protobuf-build.git#24d5a01c)`
process didn't exit successfully: `/home/pi/sdomotica/tmp/spotifyd-http/target/release/build/protobuf_build-f6ad515227645728/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"protobuf\"` did not exit successfully: exit code: 1\n--- stdout\nPackage protobuf was not found in the pkg-config search path.\nPerhaps you should add the directory containing `protobuf.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'protobuf\' found\n"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.

pi@sdomotica2:~/sdomotica/tmp/spotifyd-http $

**Comment by SimonTeixidor** [comment]
Sorry, I gave you the wrong command before. Instead of installing pulseaudio, try `apt-get install libprotobuf-dev`. You can uninstall portaudio19-dev again if you want to.

**Comment by sdomotica** [comment]
pi@sdomotica2:~/sdomotica/tmp/spotifyd-http $ cargo build --release
   Compiling tempfile v2.1.4
   Compiling protobuf_build v0.1.1 (https://github.com/plietar/rust-protobuf-build.git#24d5a01c)
   Compiling vorbisfile-sys v0.0.8
   Compiling lmdb-rs v0.7.2
   Compiling vorbis v0.0.14
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `protobuf_build v0.1.1 (https://github.com/plietar/rust-protobuf-build.git#24d5a01c)`
process didn't exit successfully: `/home/pi/sdomotica/tmp/spotifyd-http/target/release/build/protobuf_build-f6ad515227645728/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/lib/arm-linux-gnueabihf
cargo:rustc-link-lib=protobuf
cargo:rustc-link-lib=pthread
cargo:rustc-flags=-l protoc
TARGET = Some("armv7-unknown-linux-gnueabihf")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("armv7-unknown-linux-gnueabihf")
debug=false opt-level=3
HOST = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
CXX_armv7-unknown-linux-gnueabihf = None
CXX_armv7_unknown_linux_gnueabihf = None
HOST_CXX = None
CXX = None
HOST = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
CXXFLAGS_armv7-unknown-linux-gnueabihf = None
CXXFLAGS_armv7_unknown_linux_gnueabihf = None
HOST_CXXFLAGS = None
CXXFLAGS = None
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-o" "/home/pi/sdomotica/tmp/spotifyd-http/target/release/build/protobuf_build-2618bad6d5e8eed1/out/src/glue.o" "-c" "src/glue.cpp"
cargo:warning=src/glue.cpp:4:47: fatal error: google/protobuf/compiler/importer.h: No such file or directory
cargo:warning= #include <google/protobuf/compiler/importer.h>
cargo:warning=                                               ^
cargo:warning=compilation terminated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.35/src/lib.rs:897
note: Run with `RUST_BACKTRACE=1` for a backtrace.

pi@sdomotica2:~/sdomotica/tmp/spotifyd-http $

**Comment by SimonTeixidor** [comment]
Try installing `libprotoc-dev` as well. I don't run Debian myself, but it looks like that package should pull in the missing header.

**Comment by sdomotica** [comment]
one step more :-)

   Compiling syntex_syntax v0.38.0
   Compiling syntex_syntax v0.37.0
   Compiling aster v0.22.1
   Compiling hyper v0.9.10
   Compiling syntex v0.39.0
   Compiling quasi_codegen v0.16.0
Build failed, waiting for other jobs to finish...
error: Could not compile `syntex_syntax`.

To learn more, run the command again with --verbose.

**Comment by SimonTeixidor** [comment]
No error output... Maybe you ran out of memory. Try `cargo build --release -j 1`. If that doesn't work, add `--verbose` as well to see if it gives you anything more.

**Comment by sdomotica** [comment]
I tried this cargo build --release --verbose before your answer and builded!!!!
I tested on my Raspberry PI3 and works very well
Thank you so much and I posted the compiled file on my site:
www.sdomotica.com/tmp/spotifyd-http.zip
Bye
Sandro

**Comment by SimonTeixidor** [comment]
Excellent! I'll close this issue then :)
