### ISSUE TITLE
exit code: 1 when running

### ISSUE THREAD

**Issue by tavalin** [Spotifyd/spotifyd-http#3]
Managed to get it to compile but both debug and release builds error when trying to run.

```
   Compiling spotifyd-http v0.1.0 (file:///home/daniel/spotifyd-http)
    Finished debug [unoptimized + debuginfo] target(s) in 371.56 secs
     Running `debug/spotifyd-http`
error: Process didn't exit successfully: `debug/spotifyd-http` (exit code: 1)
```

Any ideas?

**Comment by SimonTeixidor** [comment]
You should run it with the same command line arguments as you would run
librespot. Otherwise, I have no ideas at the moment. Run with the
environment variable `RUST_BACKTRACE=1` and post the back trace here, I
will look into it next week :)

**Comment by tavalin** [comment]
> You should run it with the same command line arguments as you would run librespot. 

This bit wasn't obvious to me so I hadn't done that.  

So I tried again, did a clean for good measure, updated the .toml to point to your fork and then built again.  Ran using the command line arguments for librespot and the webserver started!

The REST endpoints I've tried are working and from the quick play I've been able to skip through my playlist :)

**Comment by SimonTeixidor** [comment]
Great!

The project is very immature, so there's little documentation at the
moment, as you noticed. I thought that you'd get a nicer error message than
that, though. I will improve the situation soon :)

**Comment by tavalin** [comment]
Good to hear.  

In case you're curious, the reason I came across this project (and also librespot) is that I was looking for a way to control my Spotify players from my home automation software e.g. play a playlist as a wake-up alarm. As far as I know the official web API doesn't offer Spotify Connect control so I'm hoping this project can fill that gap!

**Comment by SimonTeixidor** [comment]
Sounds cool!

I just pushed a change that will print errors, so new users should be able to figure it out now.
