### ISSUE TITLE
play playlist

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [Spotifyd/spotifyd-http#7]
Hi there,
is it also possible to initiate playing a playlist by ID?

I don't want to add the playlist's tracks to the current cue, I just want to purge whatever is currently playing and start playing a certain playlist.

Is this possible with this controller?

**Comment by SimonTeixidor** [comment]
Not directly from the playlist ID, but you can fetch the songs from Spotify's web API, and replace the current cue with a `PUT` request to `/device/tracks`, which replaces the queue (as opposed to `POST`, which appends songs).

I'll add a method for directly launching a playlist as soon as librespot supports it.

Let me know if this works out for you! 😄

**Comment by 1337sup3rh4x0r** [comment]
Thanks for the explanation!

So I'll basically need to create a script that translates a playlist ID to  track ids and then build the cue with one put, followed by n post commands.

**Comment by SimonTeixidor** [comment]
No need for `POST`.

A `PUT` with a list of IDs replaces the current cue, a `POST` with a list of IDs appends those IDs to the current cue. Otherwise you got it right!

**Comment by 1337sup3rh4x0r** [comment]
Are you talking about plietar implementing this issue: https://github.com/plietar/librespot/issues/21 ?
Would that enable you to add the method to spotifyd-http?

Actually I am a bit confused of how librespot and spotifyd-http share the work.

I was first using fornoths spotify-connect-web. There I just had to issue a play command and it would either start playing from where I left off the session before or it would somehow "fetch" what I was last listening to on another device and continue playing that.

I wish this would be possible with librespot as well. However if I issue a play command here, without adding tracks first, it stays silent.

**Comment by SimonTeixidor** [comment]
Yes, but I'm not sure if he's interested in implementing it either, seeing how this is so easy to do in a client application using the Spotify Web API.

Spotifyd-httpd just exposes APIs from (my fork of) librespot over HTTP, to make it easier for use in applications not written in Rust.

As librespot is reverse engineered, it doesn't always do the exact same thing. For now you could write a script that polls the current queue and saves it to file, and then restores it when you start a new session.

**Comment by 1337sup3rh4x0r** [comment]
I managed to build a script that fetches the track IDs of a playlist owned by me. 
However the same procedure does not seem to work for public playlists that I am following.

Do you by any chance have any experience with the Spotify api and an Idea how to handle this?

https://github.com/plamere/spotipy/issues/154

**Comment by 1337sup3rh4x0r** [comment]
I solved this now with a couple of python scripts and a cron job in the virtual machine that runs spotifyd-http.

Thank you for the hints!
